namespace: "mnecas"
name: "ovirt"
version: 0.0.3
authors:
    - Martin Necas <mnecas@redhat.com>
license:
    - MIT
tags:
    - demo
    - collection
readme: README.md
repository: https://github.com/mnecas/ansible_collections_ovirt
description: The oVirt ansible collections.
homepage: https://www.ovirt.org/
